### ISSUE TITLE
Syllabus and the assigned reading

### ISSUE THREAD

**Issue by eiahb3838ya** [hyzphbs/2019.M1.BlockChain#1]
老師您好，我是金科班一年級的胡逸凡。
1. 請問這次的 reading assignment 是哪幾章?
1. 或是如果方便的話可以將 syllabus 放上github 嗎?
---
謝謝老師的時間。

Best.
Evan Hu

**Comment by hyzphbs** [comment]
The book 1.1-1.3. The first lecture notes have been uploaded. Thanks.
